services:
  - type: web
    name: datasite
    env: node
    buildCommand: npm ci && npm --prefix backend ci --include=dev && npm --prefix frontend ci --include=dev && npm --prefix backend run build && npm --prefix frontend run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
